<section class="wrapper">
    <br>
	<div class="container">
        <div class="jumbotron">
            <h5>Jauservice</h5>
            <h1>Terminos y Condiciones</h1>
            <i>Creados: 16 de Noviembre del 2020</i>
            
            <h3>1. Relacion contractual</h3>
            <p>
            Las presentes Condiciones de uso (“Condiciones”) regulan el acceso o uso que usted haga, como persona, desde la region de las altas montañas (Orizaba, Ixtaczoquitlan, Río Blanco, Nogalez, Mendoza, Mariano Escobedo, Ixhuatlancillo y Jalapilla) de aplicaciones, páginas web, contenido y servicios (el “Servicio”) puestos a disposición por Jauservice, una empresa de responsabilidad limitada constituida en México, con domicilio social en Oriente 10, 871, Orizaba, Veracruz.
            </p>
            <h5>LEA ESTAS CONDICIONES DETENIDAMENTE ANTES DE ACCEDER O USAR el servicio</h5>
            <p>Mediante su acceso y uso del servicio usted acuerda vincularse jurídicamente por estas Condiciones, que establecen una relación contractual entre usted y Jauservice. Si usted no acepta estas Condiciones, no podrá acceder o usar el servicio. Estas Condiciones sustituyen expresamente los acuerdos o compromisos previos con usted. En caso de un incumplimiento a los presentes Términos y Condiciones por parte de usted, Jauservice podrá denegarle el acceso a su cuenta y/o a el servicio. Por otro lado, Jauservice podrá modificar o poner fin a estos Términos y Condiciones o a cualquiera del servicio ofrecidos en las aplicaciones de manera total o parcial, mediante notificación previa a través de las aplicaciones, mensaje de Whatsapp, llamada teléfonica y/o correo electrónico.</p>
            <p>Se podrán aplicar condiciones adicionales a determinados Servicios, pudiendo consistir en, de manera enunciativa mas no limitativa, políticas para un evento específico a realizarse, actividades o promociones diversas, en el entendido que dichas condiciones adicionales le serán comunicadas y notificadas en relación con el servicio a los que les resulten aplicables, teniendo en todo momento el derecho de negarse a participar en los mismos. Las condiciones adicionales se establecen además de los presentes Términos y Condiciones, y se considerarán una parte de estos para los fines del servicio aplicables. Las condiciones adicionales antes mencionadas prevalecerán sobre los presentes Términos y Condiciones, en el caso de conflicto con respecto a el servicio aplicables.</p>
            <p>Mediante notificación previa a través de las aplicaciones, mensaje de Whatsapp y/o llamada teléfonica Jauservice podrá modificar las Condiciones relativas a el servicio cuando lo considere oportuno. Las modificaciones serán efectivas después de la publicación por parte de Jauservice de dichas Condiciones actualizadas en esta ubicación o las políticas modificadas o condiciones adicionales sobre el Servicio aplicable. Su acceso o uso continuado del servicio después de dicha publicación constituye su consentimiento a vincularse por las Condiciones y sus modificaciones.</p>
            
            <h3>2. El servicio</h3>
            <p>El Servicio constituye una plataforma web que permite a los usuarios de aplicacion movil o pagina web proporcionadas como parte del servicio, agendar citas y contactar con proveedores de diferentes areas, </p>
            <h5>Licencia</h5>
            <p>Sujeto al cumplimiento de estas Condiciones, Jauservice le otorga una licencia limitada, no exclusiva, no sublicenciable, revocable, no transferible para: (I) el acceso y uso de las Aplicaciones en su dispositivo personal solo en relación con su uso del servicio; y (II) el acceso y uso de cualquier contenido, información y material relacionado que pueda ponerse a disposición a través del servicio, en cada caso solo para su uso personal, no comercial. Jauservice y sus licenciantes se reservan cualquier derecho que no haya sido expresamente otorgado por el presente.</p>
            <h5>Restricciones</h5>
            <p>Usted no podrá: (I) retirar cualquier nota de derechos de autor, marca registrada u otra nota de propiedad de cualquier parte del servicio; (II) reproducir, modificar, preparar obras derivadas sobre el servicio, distribuir, licenciar, arrendar, revender, transferir, exhibir públicamente, presentar públicamente, transmitir, retransmitir o explotar de otra forma el servicio, excepto como se permita expresamente por Jauservice; (III) descompilar, realizar ingeniería inversa o desmontar el servicio, excepto como se permita por la ley aplicable; (IV) enlazar, reflejar o enmarcar cualquier parte del servicio; (V) causar o lanzar cualquier programa o script con el objeto de extraer, indexar, analizar o de otro modo realizar prospección de datos de cualquier parte del servicio o sobrecargar o bloquear indebidamente la operación y/o funcionalidad de cualquier aspecto del servicio; o (VI) intentar obtener un acceso no autorizado o dañar cualquier aspecto del servicio o sus sistemas o redes relacionados.</p>
            <h5>Prestación de los Servicios</h5>
            <p></p>
            <h5>Servicios y contenido de Terceros</h5>
            <p>El Servicio podrá ponerse a disposición o ser accesible en relación con servicios y contenido de terceros (incluida la publicidad) que Jauservice no controle. Usted reconoce que podrán ser de aplicación diferentes condiciones y políticas de privacidad al uso que haga de dichos servicios y contenido de terceros. Jauservice no respalda dichos servicios y contenido de terceros y en ningún caso Jauservice será responsable de cualquier producto o servicio de dichos terceros proveedores. Adicionalmente, Google, Inc. y/o sus correspondientes subsidiarias o afiliados internacionales serán terceros beneficiarios en este contrato si usted accede al Servicio utilizando Aplicaciones desarrolladas para dispositivos móviles con sistema Android. Ese tercer beneficiario no es parte de este contrato y no es responsable de la prestación o apoyo de el Servicio de ninguna manera. Su acceso al Servicio utilizando estos dispositivos se sujeta a las condiciones establecidas en las condiciones de servicio del tercer beneficiario aplicable.</p>
            <h5>Titularidad</h5>
            <p>El Servicio y todos los derechos relativos a estos son y permanecerán de la propiedad de Jauservice o de sus licenciantes. Ninguna de estas Condiciones ni su uso del Servicio le transfieren u otorgan ningún derecho: (i) sobre o en relación con el Servicio, excepto en cuanto a la licencia limitada otorgada anteriormente; o bien (ii) a utilizar o mencionar en cualquier modo a los nombres de empresa, logotipos, nombres de producto y servicio, marcas comerciales o marcas de servicio de Jauservice o de sus licenciantes.</p>
            
            <h3>3. El uso del servicio</h3>
            <h5>Cuentas de usuario.</h5>
            <p>Con el fin de usar la mayor parte de los aspectos del Servicio, usted debe registrarse y mantener activa una cuenta personal de usuario del Servicio (“Cuenta”). Para obtener una Cuenta debe tener como mínimo 18 años, o tener la mayoría de edad legal en su jurisdicción (si es distinta a los 18 años). El registro de la cuenta le requiere que comunique a Jauservice determinada información personal, como su nombre, dirección y número de teléfono móvil. Usted se compromete a mantener la información en su Cuenta de forma exacta, completa y actualizada. Si no mantiene la información de Cuenta de forma exacta, completa y actualizada, de no ser así podrá resultar en su imposibilidad para acceder y utilizar el Servicio o en la resolución por parte de Jauservice de estas Condiciones. Usted es responsable de toda la actividad que ocurre en su Cuenta y se compromete a mantener en todo momento de forma segura y secreta el nombre de usuario y la contraseña de su Cuenta. A menos que Jauservice permita otra cosa por escrito, usted solo puede poseer una Cuenta.</p>
            <h5>Requisitos y conducta del usuario.</h5>
            <p>El Servicio no está disponible para el uso de personas menores de 18 años. Usted no podrá autorizar a terceros a utilizar su Cuenta, asimismo no podrá permitir a personas menores de 18 años que reciban servicios a menos que aquellos sean acompañados por usted. No podrá ceder o transferir de otro modo su Cuenta a cualquier otra persona o entidad. Usted acuerda cumplir con todas las leyes aplicables al utilizar los Servicios y solo podrá utilizar los Servicios con fines legítimos (p. ej., no para el transporte de materiales ilegales o peligrosos). En el uso de los Servicios, no causará estorbos, molestias, incomodidades o daños a la propiedad, tanto al Tercero proveedor como a cualquier otra parte. En algunos casos, se le podrá requerir que facilite un documento de identidad u otro elemento de verificación de identidad para el acceso o uso de el Servicio, y usted acepta que se le podrá denegar el acceso o uso de el Servicio si se niega a facilitar el documento de identidad o el elemento de verificación de identidad.</p>
            <h5>Mensaje de whatsapp.</h5>
            <p>Al crear una Cuenta, usted acepta que el Servicio le pueda enviar mensajes de whatsapp informativos como parte de la actividad comercial normal de su uso del Servicio.</p>
            <h5>Llamadas teléfonicas.</h5>
            <p>Al crear una Cuenta, usted acepta que nuestro personal se podrá poner en contacto con usted mediante llamadas telefénicas al teléfono que nos ha proporcionado, con el fin de corroborar su experiencia y dar seguimiento al uso de su servicio.</p>

            <h3>4. Soporte; Renuncias; Limitación de responsabilidad; Indemnidad.</h3>
            <h5>Soporte</h5>
            <p>Jauservice brinda soporte los 365 días del año, en caso de que lo necesite. Para recibir soporte, puede ingresar a la sección de <a href="https://www.jauservice.com/index.php/welcome/contact">Contáctanos</a> o iniciando sesión e ir a la sección de Ayuda en su cuenta.</p>

            <h5>Renuncia</h5>
            <p>El Servicio se proporcionan “tal cual” y “como disponible”. Jauservice renuncia a toda declaración y garantía, expresa, implícita o estatutaria, no expresamente establecida en estas condiciones, incluidas las garantías implícitas de comerciabilidad, idoneidad para un fin particular y no violación. Además, Jauservice no hace declaración ni presta garantía alguna relativa a la fiabilidad, puntualidad, calidad, idoneidad o disponibilidad de los servicios o cualquiera de los servicios o bienes solicitados a través del uso del servicio, o que el servicio no será interrumpido o estará libre de errores. Jauservice no garantiza la calidad, idoneidad, seguridad o habilidad de los terceros proveedores. Usted acuerda que todo riesgo derivado de su uso de los servicios y cualquier servicio o bien solicitado en relación con aquellos será únicamente suyo, en la máxima medida permitida por la ley aplicable.</p>
            
            <h5>LIMITACIÓN DE RESPONSABILIDAD</h5>
            <p>Jauservice no será responsable de daños indirectos, incidentales, especiales, ejemplares, punitivos o emergentes, incluidos el lucro cesante, la pérdida de datos, la lesión personal o el daño a la propiedad, ni de perjuicios relativos, o en relación con, o de otro modo derivados de cualquier uso de los servicios, incluso aunque Jauservice haya sido advertido de la posibilidad de dichos daños. Jauservice no será responsable de cualquier daño, responsabilidad o pérdida que deriven de: (I) Su uso o dependencia de los servicios o su incapacidad para acceder o utilizar los servicios; o (ii) Cualquier transacción o relación entre usted y cualquier tercero proveedor, aunque Jauservice hubiera sido advertido de la posibilidad de dichos daños. Jauservice no será responsable del retraso o de la falta de ejecución resultante de causas que vayan más allá del control razonable de Jauservice.</p>
            <!--<p>En ningún caso la responsabilidad total de Jauservice hacia usted en relación con los servicios por todos los daños, las pérdidas y los juicios podrá exceder de quinientos euros (€500) o su equivalente en moneda nacional.</p>-->
            <p>Usted podrá utilizar los servicios de Jauservice para solicitar y planificar servicios de casa o logísticos con terceros proveedores, pero acepta que Jauservice no tiene responsabilidad alguna hacia usted en relación con cualquier servicio de casa o logístico prestado a usted por terceros proveedores que no sea como se ha establecido expresamente en estas condiciones.</p>
            
            <h5>Indemnidad</h5>
            <p>Usted acuerda mantener indemnes y responder frente a Jauservice y sus consejeros, directores, empleados y agentes por cualquier reclamación, demanda, pérdida, responsabilidad y gasto (incluidos los honorarios de abogados) que deriven de: (i) su uso del Servicio o servicios a través de su uso del Servicio; (ii) su incumplimiento o violación de cualquiera de estas Condiciones; (iii) el uso por parte de Jauservice de su Contenido de usuario; o (iv) su infracción de los derechos de cualquier tercero, incluidos Terceros proveedores.</p>
            
            <h3>5. Legislación aplicable; Resolución Directa y Arbitraje.</h3>
            <p>En caso de que usted tenga algún problema con el uso del Servicio y/o considere que alguna parte de las presentes Condiciones no está siendo observada o cumplida por Jauservice y/o el Tercero proveedor, o de presentarse cualquier diferencia entre las Partes derivada o relacionada con las presentes Condiciones, usted acepta que el proceso a seguir consiste en comunicar dicha situación a través de la sección ubicada en el menú de su cuenta de la aplicación denominada “Ayuda” o bien desde la sección de <a href="https://www.jauservice.com/index.php/welcome/contact">Contáctanos</a>, con el propósito de analizar y resolver el caso concreto.</p>
            <p>En el supuesto en que usted considere que la resolución del caso no es conforme a sus intereses, las Partes acuerdan que dicha disputa será resuelta de manera definitiva de conformidad a lo siguiente:</p>
            
            <!--
            <h5>Mediación y Arbitraje</h5>
            <p></p>
            -->
            <p></p>
        </div>
	</div>
</section>
